### ISSUE TITLE
feat: add coverage test for dotnet projects

### ISSUE THREAD

**Issue by HamidMolareza** [Payadel/pre-commit-hooks#42]
Sample: 
```
- repo: https://github.com/Payadel/pre-commit-hooks
  rev: v1
  hooks:
    - id: dotnet-coverage
      args: [ --path='/path/to/project', --min=50 ]
      stages: [ push ]
      pass_filenames: false
```

## TODO

- Add to [ConsoleSharpTemplate](https://github.com/Payadel/ConsoleSharpTemplate)
- Add to [NugetPackageTemplate](https://github.com/Payadel/NugetPackageTemplate)
